### ISSUE TITLE
是否考虑校历？

### ISSUE THREAD

**Issue by Gompyn** [pkuhelper-web/syllabus#1]
当前生成结果似乎不考虑校历，如在国庆期间依然显示有课，感觉不太方便，能否加上相关选项？

**Comment by xmcp** [comment]
生成结果是考虑了校历的，不信导入到Outlook里看下，国庆和中秋是没有课的。

问题在于除Outlook以外的大多数日历软件不支持重复事件暂停的功能。

**Comment by Gompyn** [comment]
在Outlook中发现国庆确实没课了，但中秋有课——中秋前一天没课，似乎搞反了。

**Comment by xmcp** [comment]
应该是时区的问题，修了
