### ISSUE TITLE
双学位的同学在利用选课系统导入课表的时候似乎无法进行两次操作

### ISSUE THREAD

**Issue by alisomia** [pkuhelper-web/syllabus#4]

**Comment by xmcp** [comment]
不懂你说的是什么意思

**Comment by alisomia** [comment]
就是我在用“课表助手” 的 “从选课系统导入课表的时候” 我的主修学位和辅修学位的选课结果是分开的。但是我复制其中一个学位的结果的时候会自动帮我读入，似乎除了手动没什么办法导入辅修的选课结果？

**Comment by xmcp** [comment]
导入其中一个表格之后可以点返回重新进入导入页面，就可以再导入另一个
